sudo: false
language: node_js

os:
  - linux
  - osx

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"

install:
  - export PATH=./node_modules/.bin/:$PATH

script:
  - npm install --build-from-source --node-gyp=$(which pangyp)
  - "./node_modules/.bin/node-pre-gyp package"
  - echo $TRAVIS_TAG
  - echo $TRAVIS_PULL_REQUEST
  - > 
    ([[ "$TRAVIS_TAG" =~ ^v[0-9] ]] &&
    test "$TRAVIS_PULL_REQUEST" = false &&
    ./node_modules/.bin/node-pre-gyp publish) || true
