sudo: false

os:
  - linux
  - osx

env:
  global:
    - secure: VwwHS3ZYxu5WudTcWRw588aekYZrTHMDvziNWLhPnadVs+ami6EF7CMHFZenkvSehmmaunKaH0vcNuxDXqLjrZN8Qt6aOuVVq9o/N6+8OG6/E2D0lDRFF9OZdAKetzS7EtoZfVJpqe009leg9V5mjx3uo1WRlc6SqmeKynaUDaY=
  matrix:
    - NODE_VERSION="0.8"
    - NODE_VERSION="0.10"
    - NODE_VERSION="0.12"
    - NODE_VERSION="iojs-v1.0"
    - NODE_VERSION="iojs-v1"
    - NODE_VERSION="iojs-v2"

matrix:
  include: 
    - os: linux
      env: CXX="g++-4.8" NODE_VERSION="iojs-v3"
    - os: linux
      env: CXX="g++-4.8" NODE_VERSION="4"
    - os: osx
      env: NODE_VERSION="iojs-v3"
    - os: osx
      env: NODE_VERSION="4"

addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - libudev-dev
    - gcc-4.8
    - g++-4.8

before_install:
  - npm install -g npm
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm config set python `which python`

install:
  - export PATH=./node_modules/.bin/:$PATH

script:
  - npm install --build-from-source
  - npm run package-binary
  - echo $TRAVIS_TAG
  - echo $TRAVIS_PULL_REQUEST
  - > 
    ([[ "$TRAVIS_TAG" =~ ^v[0-9] ]] &&
    test "$TRAVIS_PULL_REQUEST" = false &&
    ./node_modules/.bin/node-pre-gyp publish) || true
