sudo: false
language: node_js

os:
  - linux
  - osx

env:
  global:
    - secure: VwwHS3ZYxu5WudTcWRw588aekYZrTHMDvziNWLhPnadVs+ami6EF7CMHFZenkvSehmmaunKaH0vcNuxDXqLjrZN8Qt6aOuVVq9o/N6+8OG6/E2D0lDRFF9OZdAKetzS7EtoZfVJpqe009leg9V5mjx3uo1WRlc6SqmeKynaUDaY=
  matrix:
    - CXX=g++-4.8

node_js:
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "0.8"

addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - libudev-dev
    - gcc-4.8
    - g++-4.8

script:
  - npm install --build-from-source
  - npm run package-binary
  - echo $TRAVIS_TAG
  - echo $TRAVIS_PULL_REQUEST
  - > 
    ([[ "$TRAVIS_TAG" =~ ^v[0-9] ]] &&
    test "$TRAVIS_PULL_REQUEST" = false &&
    ./node_modules/.bin/node-pre-gyp publish) || true
